<?php
/* @var $this yii\web\View */

$this->title = 'Dashboard';
$user = Yii::$app->user->identity;
$baseURL = Yii::$app->params['BASE_URL'];
$imageURL = Yii::$app->params['IMAGE_URL'];
?>
<main class="mn-inner">
    <div class="col s12 m12 l12">

        <div class = "row">
            <div class = "col s12 m12 l12">
                <div class="card white darken-1">
                    <div class="card-content">
                        <span class="card-title">Privacy Policy</span>
                        <div style="font-size:13px">
                          <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Your privacy is important to us, and we are committed to protecting the personal information you choose to share with us. This Privacy Policy applies to all of the products, services, and websites offered by Project TRT, LLC. This Privacy Policy explains how we collect, use, protect, and share information when you use the ProjectTRT.com website, located at projecttrt.com (the </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="de-DE">Site</span></span></span></span><span style=""><span style=""><span style="">&rdquo;).</span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">By using the Site, you consent to this Privacy Policy. This Privacy Policy does not apply to the practices of third parties that Project TRT does not own, control, manage, or employ.</span></span></span></span></span></span></span></p><br>    
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">Information We Collect through the Site</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Personally Identifiable Information:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We collect information that personally identifies you. This information may include, but not be limited to your name, username, email address, occupation, industry, country of origin or credit card details, and other information as we may from time to time request at our discretion (</span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Personally Identifiable Information</span></span></span></span><span style=""><span style=""><span style="">&rdquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">), including information from third parties, only if you choose to share such information with us. For example, you may be asked to provide us with certain Personally Identifiable Information when you register with or use our services, when you register with or use the Site, when you correspond with us and at other times . The decision to provide this information is optional; however, if you elect not to register with or provide such information, you may not be able to access certain content, features, or services available on or through the Site. We reserve the right to send you certain communications relating to Project TRT</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s services, such as service announcements, administrative messages, special promotions, and newsletters, which are considered part of your account, without offering you the opportunity to opt out of receiving them.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Non-Personally Identifiable Information:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We automatically collect Non-Personally Identifiable Information when you use the Site, which may include anonymous identifiers associated with your mobile device. Non-Personally Identifiable Information includes demographic information (such as age, gender, city, state or behavioral data) and a user</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s click stream information. Click stream data is anonymous and can include information such as your IP address, web pages viewed, the date and time at which those pages were viewed and interaction with content and advertisements on those web pages. Technologies used to collect this click stream data include cookies and web beacons. We collect Non-Personally Identifiable Information and store it in log files. We use this information to help us understand how people use our Site. For example, each time you use the Site we automatically collect the type of web browser you use, your operating system, your ISP, which pages you view, and the time and duration of your visits to the Site.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We may augment our click stream data with Non-Personally-Identifiable Information from third party Services Providers (defined below) to target and serve some of the advertisements you may see on the pages of our Site . We utilize the non-personal information described above to better customize the sort of advertisements you see. This information also may be used to help measure and research an advertisement</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s effectiveness, or for other purposes. We also aggregate anonymous cookie data in order to identify large audience segments that assist advertisers in targeting their campaigns to the most relevant Internet audience.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The use and collection of information by our third-party advertising Service Providers is governed by the individual privacy policies of those providers.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Many of our advertising Service Providers are members of the National Advertising Initiative (</span></span></span></span><span style=""><span style=""><span style="">&ldquo;NAI&rdquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">). You can obtain more information about these advertising service providers</span></span></span></span><span style=""><span style=""><span style="">&rsquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">information collection practices, and opt out of such practices (and at the same time opt out of the collection practices of other, or all, NAI members) by following the opt out instructions on the NAI</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s website at:</span></span></span></span><span style=""><span style=""><span style="">&nbsp;</span></span></span><span style="color: #00aaca;"><a href="http://www.networkadvertising.org/managing/opt_out.asp"><span style=""><span style=""><span lang="en-US">http://www.networkadvertising.org/managing/opt_out.asp</span></span></span></a></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Cookies and Web Beacons:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We may use cookies (a small text file placed on your computer to identify your computer and browser), web beacons (an electronic file placed on a website that monitors usage), and other similar technologies to improve the quality of the Site and to better target and analyze consumer behavior with the goal of providing better and more relevant advertising. Our cookie does not include your name or anything personal to you. It simply tells us that we have encountered your computer at some prior point. Most web browsers are initially set up to accept cookies. You can reset your web browser to refuse all cookies or to indicate when a cookie is being sent. However, certain features of the Site may not work if you delete or disable cookies. Alternatively, you are always free to opt out of the cookies.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Some of our Service Providers may use their own cookies and web beacons in connection with the services they perform on our behalf. If you would like more information about these practices and to know your choices about not having this information used by these companies, please click here.</span></span></span></span></span></span></span></p><br>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">Information You Choose to Display Publicly on Our Site</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You may elect to publicly post Personally Identifying Information about yourself, or otherwise share Personally Identifying Information about yourself with other registered users of the Site, in the normal use of your usage of the Site. This could occur through use of services that may include optional profile fields, in interactions on public boards, wikis, cases and forums, or if a previously private interaction is made public.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Information like that, which is voluntarily posted in publicly visible parts of our Site or that is shared with other registered users, (a) is considered to be public, even if it would otherwise be considered to be Personally Identifying Information, and (b) will remain on our Site (and in the case of information shared with other registered users, available to those users) even after you terminate your account with us. As such, it is not subject to the protocols listed below, because we don</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">t control it; you do. Additionally, voluntarily publicizing such information or sharing it with other registered users means that you lose any privacy rights you might normally have with regards to that information. It may also increase your chances of receiving unwanted communications, like spam.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Please also remember that if you choose to provide Personally Identifiable Information using certain public features of the Site, or with other registered users of the Site, individuals reading such information may use or disclose it to other individuals or entities without our control and without your knowledge, and search engines may index that information. We therefore urge you to think carefully about including any specific information you may deem private in content that you create or information that you submit through our Site.</span></span></span></span></span></span></span></p><br>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">How We Use and Share Information Collected through the Site</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="">General:</span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We use Personally Identifiable Information and Non-Personally Identifiable Information for internal purposes only, such as to notify you of new products or services, to send service notifications, to customize the advertising and content you see, to fulfill your requests for products and services, to improve the Site, to conduct research, to solicit your feedback and input about the Site, and to provide more relevant and effective products, services, and advertisements on or through the Site. Personally Identifiable Information and Non-Personally Identifiable Information may be combined with data collected from other sources so that we may further improve the relevance and effectiveness of products, services, and advertisements offered on or through the Site. We will not sell, share, or rent Personally Identifiable Information and Non-Personally Identifiable Information to third parties, and we will not otherwise disclose Personally Identifiable Information and Non-Personally Identifiable Information to third parties, without your permission, except as expressly disclosed in this Privacy Policy.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Service Providers:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We may share Personally Identifiable Information with our service providers that help us provide the services that you request (</span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Service Providers</span></span></span></span><span style=""><span style=""><span style="">&rdquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">). For example, we may contract with Service Providers to provide certain services, such as credit card processing, advertising, analytics tools, data management services, web hosting, and web development. We provide our Service Providers with the information needed for them to perform these services, however, each Service Provider must agree to implement and maintain reasonable security procedures and practices appropriate to the nature of the information involved in order to protect your information from unauthorized access, destruction, use, modification or disclosure.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">Data Storage:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We use outside vendors and hosting companies to provide the necessary hardware, software, networking, storage, and related technology required to run our Site and services. We retain full rights of ownership on our software, designs, code, databases and any other internally developed application to provide the service. Subject to the terms of this policy, you retain full rights of your data posted on the service.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Non-Personally Identifiable Information Only:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We may use, and disclose to third parties, certain Non-Personally Identifiable Information regarding the Site (e.g., number of visits, page views, and the like) without your permission. However, such information does not identify you individually.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Other Transfers:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We may share Personally Identifiable Information and Non-Personally Identifiable Information with businesses controlling, controlled by, or under common control with our company. If Project TRT is merged, acquired, or sold, or in the event of a transfer of some or all of our assets, we may disclose or transfer Personally Identifiable Information and Non-Personally Identifiable Information in connection with such transaction. You will have the opportunity to opt out of any such transfer if, in our discretion, the new entity plans to handle your information in a way that differs materially from this Privacy Policy.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Compliance with Laws and Law Enforcement:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Our company will work with government and law enforcement officials and private parties to enforce and comply with the law. We reserve the right to disclose Personally Identifiable Information and Non-Personally Identifiable Information to government or law enforcement officials or private parties if, in our discretion, we believe it is necessary or appropriate in order to respond to legal requests (including court orders and subpoenas), to protect the safety, property or rights of Project TRT or of any third party, to prevent or stop any illegal, unethical, or legally actionable activity, or to comply with the law.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Educational Institutions and FERPA:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">For Users subject to Family Educational Rights and Privacy Act, 20 U.S.C. </span></span></span></span><span style=""><span style=""><span style="">&sect; 1232g (FERPA) </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Project TRT acknowledges that for the purpose of our Terms of Service, that it is a </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">school official</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">with </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">legitimate educational interests</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">in customer data and agrees to abide by FERPA requirements on school officials imposed by 34 CFR 99.33(a). Project TRT only uses customer data to provide the service, including purposes compatible with providing the service, and will not use customer data for any advertising or similar commercial purposes.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The User understands that Project TRT may possess limited or no contact information for User</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s students and students</span></span></span></span><span style=""><span style=""><span style="">&rsquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">parents. Consequently, User will be responsible for obtaining any parental consent for any end user</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s use of the Services that may be required by applicable law and to convey notification on behalf of Project TRT to students (or, with respect to a student under 18 years of age and not in attendance at a postsecondary institution, to the student</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s parent) of any judicial order or lawfully-issued subpoena requiring the disclosure of User Data in Project TRT</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s possession as may be required under applicable law.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Certain Data Retention:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We do not keep certain data on our own servers; instead the data is kept on the End User</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s computer in Project TRT</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s cookie. The data is stored in the cookie until the cookie is deleted by the End User. End Users can delete the cookie at any time, as explained in this Privacy Policy.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Third Party Websites:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The Site may contain links to websites or content operated and maintained by third parties. We do not control those sites or their privacy practices, which may differ from our practices. If you click on a link or an advertisement, the privacy policy of the website to which you link will govern the collection and use of your information by that website</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s operator(s). You access such third-party websites or content at your own risk. You should always read the privacy policy of a third-party website before disclosing any information to the website. </span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Spyware or Adware:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">These terms refer to applications that are downloaded to your computer. These types of applications deliver ads (usually in the form of pop-up type ads) based on your web usage. We do not participate in any way with spyware or adware applications, and we do not download these types (or any types) of applications without your expressed acceptance. Cookies and .swf files are not spyware or adware, and they are not harmful to your computer.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Security:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We recognize the importance of safeguarding the confidentiality of your information. Accordingly, we employ standard security measures designed to protect your information from unauthorized access. However, no data transmission over the Internet or other network can be guaranteed to be 100% secure. Therefore, while we strive to protect any information you transmit on or through the Site, please be advised that our company assumes no responsibility or liability for disclosure of your information due to errors in transmission, unauthorized third-party access, or other causes beyond our company</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s reasonable control.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Processing in the United States:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">By using our Site, you agree that the collection, use, transfer, and disclosure of your Personally Identifiable Information will be governed by the applicable laws in the United States.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Children</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s Privacy Statement:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The Site is directed to, and intended for use by, adults only. We do not knowingly collect information from children under the age of 13. If we become aware that we have inadvertently received information from a child under the age of 13, we will delete such information from our records. Because we do not knowingly collect any information from children under the age of 13, we also do not knowingly distribute such information to third parties.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Privacy Policy Changes:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We may update this Privacy Policy from time to time, and so you should review this Policy periodically. If we decide to change this Privacy Policy, we will inform you by posting the revised Privacy Policy on the Site. Those changes will go into effect on the Revision Date shown at the top of the revised Privacy Policy. Your continued use of the Site constitutes your consent to the revised Privacy Policy.</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Acceptance of Privacy Policy:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">When you use the Site, you are accepting the terms and conditions of this Privacy Policy, and we will have the right to use your information as described in this Privacy Policy. If you do not agree to have your information used in any of the ways described in this Privacy Policy, you must discontinue use of the Site. You can also access, correct, or change your Personally Identifiable Information, or opt out of our direct marketing efforts, by sending an email to info@projecttrt.com. Once a request to opt out has been received, we will send a confirming email message to the user that the user</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s Personally Identifiable Information has been successfully opted out of our database. If you do not receive this confirmatory email, then please contact us to ensure that your request was received and processed. If you have questions or concerns about this Privacy Policy, please email us at info@projecttrt.com or send us a letter at:</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Project TRT</span></span></span></span><span style=""><span style=""><span style=""><span lang="da-DK">, LLC,</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Attention: Privacy</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">21318 61st St Ct E</span></span></span></span></span></span></span></p>
<p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Bonney Lake, WA 98391</span></span></span></span></span></span></span></p>
                        </div>
                    </div>
                </div>


            </div>
        </div>

</main>