<?php
/* @var $this yii\web\View */

$this->title = 'Dashboard';
$user = Yii::$app->user->identity;
$baseURL = Yii::$app->params['BASE_URL'];
$imageURL = Yii::$app->params['IMAGE_URL'];
?>
<main class="mn-inner">
    <div class="col s12 m12 l12">

        <div class = "row">
            <div class = "col s12 m12 l12">
                <div class="card white darken-1">
                    <div class="card-content">
                        <span class="card-title">Terms & Conditions</span>
                        <div style="font-size:13px">
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">THIS AGREEMENT GOVERNS YOUR ACQUISITION AND USE OF OUR SERVICES.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">IF YOU REGISTER FOR A FREE TRIAL FOR OUR SERVICES, THIS AGREEMENT WILL ALSO GOVERN THAT FREE TRIAL.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">BY ACCEPTING THIS AGREEMENT, EITHER BY CLICKING A BOX INDICATING YOUR ACCEPTANCE OR BY EXECUTING AN ORDER FORM THAT REFERENCES THIS AGREEMENT, YOU AGREE TO THE TERMS OF THIS AGREEMENT.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">IF YOU ARE ENTERING INTO THIS AGREEMENT ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO BIND SUCH ENTITY AND ITS AFFILIATES TO THESE TERMS AND CONDITIONS, IN WHICH CASE THE TERMS </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">YOU</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="de-DE">OR </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">YOUR</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">SHALL REFER TO SUCH ENTITY AND ITS AFFILIATES. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT AGREE WITH THESE TERMS AND CONDITIONS, YOU MUST NOT ACCEPT THIS AGREEMENT AND MAY NOT USE THE SERVICES.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You may not access any of Our services if You are Our direct competitor, except with Our prior written consent. In addition, You may not access the Services for purposes of monitoring their availability, performance or functionality, or for any other benchmarking or competitive purposes.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">This Agreement was last updated on August 3, 2018. It is effective between You and Us as of the date of You accepting this Agreement.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">1. DEFINITIONS</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">Affiliate</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means any entity that directly or indirectly controls, is controlled by, or is under common control with the subject entity. </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="it-IT">Control,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">for purposes of this definition, means direct or indirect ownership or control of more than 50% of the voting interests of the subject entity.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Agreement</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means this Subscription Agreement.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="fr-FR">Alpha Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; or &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Beta Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">each mean Services that are not generally available to customers.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">Content</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means information obtained by Us from Our content licensors or publicly available sources and provided to You pursuant to an Order Form, as more fully described in the Documentation.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="fr-FR">Documentation</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means Our online user guides, documentation, and help and training materials, as updated from time to time, accessible via propared.com or login to the applicable Service.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Free Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means the products and Services that are ordered by You and made available online by Us for free, including associated offline components, as described in the Documentation. </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Free Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">exclude Purchased Services, Content and Non-Propared.com Applications.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Malicious Code</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means code, files, scripts, agents or programs intended to do harm, including, for example, viruses, worms, time bombs and Trojan horses.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Marketplace</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means an online directory, catalog or marketplace of applications that interoperate with the Services.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="de-DE">Non-Propared.com Applications</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means a web-based or offline software application that is provided by You or a third party and interoperates with a Service, including, for example, an application that is developed by or for You, is listed on a Marketplace, or is identified by Us as such.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="de-DE">Order Form</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means an ordering document specifying the Services to be provided hereunder that is entered into between You and Us or any of Our Affiliates, including any addenda and supplements thereto. By entering into an Order Form hereunder, an Affiliate agrees to be bound by the terms of this Agreement as if it were an original party hereto.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Purchased Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means Services that You or Your Affiliate purchase under an Order Form, as distinguished from those provided pursuant to a free trial.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means the products and services that are ordered by You under a free trial or an Order Form and made available online by Us, including associated offline components, as described in the Documentation. </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">exclude Content and Non-Propared.com Applications.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Subscription</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means a subscription for use of any Service.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">User</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means an individual who registers to use a Service, or who is authorized by You to use a Service on Your behalf, each having a user identification and password. Users may include, for example, Your employees, consultants, contractors and agents, and third parties with which You transact business.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="de-DE">We,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; &ldquo;Us&rdquo; or &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Our</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means the Project TRT LLC.</span></span></span></span><span style=""><span style=""><span style="">, a </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Washington limited liability company.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You</span></span></span></span><span style=""><span style=""><span style="">&rdquo; or &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Your</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means the person or company or other legal entity for which you are accepting this Agreement, and Affiliates of that company or entity.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Your Data</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means electronic data and information submitted by or for You to Services or collected and processed by or for You using the Services or Purchased Services, excluding Content and Non-Propared.com Applications.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="de-DE">2. FREE TRIAL</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">If You register on our website for a free trial, We will make one or more Services available to You on a trial basis free of charge until the earlier of (a) the end of the free trial period for which you registered to use the applicable Service(s), or (b) the start date of any Purchased Service Subscriptions ordered by You for such Service(s). Additional trial terms and conditions may appear on the registration web page for such Services. Any such additional terms and conditions are incorporated into this Agreement by reference and are legally binding. If you do not purchase a Subscription to the same services as those covered by the trial, we reserve the right to, among other things, restrict the functionality of the Services or otherwise restrict your access to the Services entirely.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">NOTWITHSTANDING SECTION 9 (REPRESENTATIONS, WARRANTIES, EXCLUSIVE REMEDIES AND DISCLAIMERS), DURING THE FREE TRIAL THE SERVICES ARE PROVIDED </span></span></span></span><span style=""><span style=""><span style="">&ldquo;AS-IS&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">WITHOUT ANY WARRANTY.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Please review the user guides provided during the trial period so that You become familiar with the features and functions of the Services before You make Your purchase.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">3. OUR RESPONSIBILITIES</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">3.1. Provision of Purchased Services.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We will (a) make the Services and Content available to You pursuant to this Agreement and the applicable Order Forms, (b) provide Our standard support for the Purchased Services to You at no additional charge, and/or upgraded support to the extent offered by Us and if purchased by You, and (c) use commercially reasonable efforts to make the online Purchased Services available 24 hours a day, 7 days a week, except for: (i) planned downtime (of which We shall give at least 8 hours electronic notice and which We shall schedule to the extent practicable during the hours between midnight and 5:00am eastern standard time), and (ii) any unavailability caused by circumstances beyond Our reasonable control, including, for example, an act of God, act of government, flood, fire, earthquake, civil unrest, act of terror, strike or other labor problem (other than one involving Our employees), Internet service provider failure or delay, Non-projecttrt.com Application, or denial of service attack.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">3.2. Protection of Your Data.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We will maintain administrative, physical, and technical safeguards for protection of the security, confidentiality and integrity of Your Data, including as is described in our Privacy Policy, which is incorporated herein by reference. Those safeguards will include, but will not be limited to, measures for preventing access, use, modification or disclosure of Your Data by Our personnel except (a) to provide the Services and prevent or address service or technical problems, (b) as compelled by law in accordance with Section 8.3 (Compelled Disclosure) below, or (c) as You expressly permit in writing.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Unless you purchase a Purchased Service, You may not be able to migrate Your data from a Free Service to a Purchased Service.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">AT THE CONCLUSION OF A FREE TRIAL, OR WITH RESPECT TO YOUR USE OF FREE SERVICES, IN THE EVEN THAT YOU DO NOT LOGIN TO YOUR ACCOUNT FOR A PERIOD OF 30 DAYS, WE RESERVE THE RIGHT TO PERMANENTLY DELETE ANY DATA YOU ENTER INTO THE SERVICES, AND ANY CUSTOMIZATIONS MADE TO THE SERVICES BY OR FOR YOU UNLESS YOU PURCHASE A SUBSCRIPTION TO THE SAME SERVICES AS THOSE COVERED BY THE FREE TRIAL, OR PURCHASE UPGRADED SERVICES.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">3.3 Our Personnel.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We will be responsible for the performance of Our personnel (including Our employees and contractors) and their compliance with Our obligations under this Agreement, except as otherwise specified herein.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">3.4 Alpha &amp; Beta Services.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">From time to time, We may invite You to try Alpha or Beta Services at no charge or for a discounted rate. You may accept or decline any such trial in Your sole discretion. Alpha or Beta Services will be clearly designated as alpha, beta, pilot, limited release, developer preview, non-production, evaluation or by a description of similar import. Alpha and Beta Services are for evaluation purposes and not for production use, are not considered </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">under this Agreement, are not supported, and may be subject to additional terms. Unless otherwise stated, any Alpha and Beta Services trial period will expire upon the earlier of one year from the trial start date or the date that a version of the Alpha or Beta Services becomes generally available. We may discontinue Alpha or Beta Services at any time in Our sole discretion and may never make them generally available. We will have no liability for any harm or damage arising out of or in connection with an Alpha or Beta Service.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="">3.5 Free Services.</span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We may offer Free Services at no charge. You may accept or decline any such Free Services in Your sole discretion. Free Services will be clearly designated as such. Free Services are not considered </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Services</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">under this Agreement, are not supported, and may be subject to additional terms. We may discontinue Free Services at any time in Our sole discretion and may never make them generally available. We will have no liability for any harm or damage arising out of or in connection with a Free Service.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">WE WILL USE REASONABLE EFFORTS, IN OUR SOLE DISCRETION, TO PROVIDE YOU WITH ADVANCE NOTICE VIA EMAIL IN THE EVENT WE INTEND TO DISCONTINUE FREE SERVICES.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">NOTWITHSTANDING SECTION 9 (REPRESENTATIONS, WARRANTIES, EXCLUSIVE REMEDIES AND DISCLAIMERS), THE FREE SERVICES ARE PROVIDED </span></span></span></span><span style=""><span style=""><span style="">&ldquo;AS-IS&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">WITHOUT ANY WARRANTY.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">4. USE OF SERVICES AND CONTENT</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">4.1 Subscriptions.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Unless otherwise provided in the applicable Order Form, (a) Services and Content are purchased as Subscriptions, (b) Subscriptions may be added during a Subscription term at the same pricing as the underlying Subscription pricing, prorated for the portion of that Subscription term remaining at the time the Subscriptions are added, and (c) any added Subscriptions will terminate on the same date as the underlying Subscriptions.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">4.2 Usage Limits.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Free Services, Services, Purchased Services and Content may be subject to usage limits, including, for example, the quantities specified in Order Forms. Unless otherwise specified, (a) a quantity in an Order Form refers to Users, and the Free Service, Service, Purchased Service or Content may not be accessed by more than that number of Users, (b) a User</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s password may not be shared with any other individual, and (c) a User identification may be reassigned to a new individual replacing one who no longer requires ongoing use of the Free Service, Service, Purchased Service or Content. If You exceed a contractual usage limit, We may work with You to seek to reduce Your usage so that it conforms to that limit. If, notwithstanding Our efforts, You are unable or unwilling to abide by a contractual usage limit, You will execute an Order Form for additional quantities of the applicable Free Service, Service, Purchased Service or Content promptly upon Our request, and/or pay any invoice for excess usage in accordance with Section 6.2 (Invoicing and Payment).</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">4.3 Your Responsibilities.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You will (a) be responsible for Users</span></span></span></span><span style=""><span style=""><span style="">&rsquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">compliance with this Agreement, (b) be responsible for the accuracy, quality and legality of Your Data and the means by which You acquired Your Data, (c) use commercially reasonable efforts to prevent unauthorized access to or use of Services and Content, and notify Us promptly of any such unauthorized access or use, (d) use Services and Content only in accordance with the Documentation and applicable laws and government regulations, and (e) comply with terms of service of Non-Propared.com Applications with which You use a Free Service, Service, Purchased Service or Content.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="fr-FR">4.4 Usage Restrictions.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You will not (a) make any Free Service, Service, Purchased Service or Content available to, or use any Service or Content for the benefit of, anyone other than You or Users, (b) sell, resell, license, sublicense, distribute, rent or lease any Free Service, Service, Purchased Service or Content, or include any Free Service, Service, Purchased Service or Content in a service bureau or outsourcing offering, (c) use a Free Service, Service, Purchased Service or Content to store or transmit infringing, libelous, or otherwise unlawful or tortious material, or to store or transmit material in violation of third-party privacy rights, (d) use a Free Service, Service, Purchased Service or Content to store or transmit Malicious Code, (e) interfere with or disrupt the integrity or performance of any Service or third-party data contained therein, (f) attempt to gain unauthorized access to any Free Service, Service, Purchased Service or Content or its related systems or networks, (g) permit direct or indirect access to or use of any Free Service, Service, Purchased Service or Content in a way that circumvents a contractual usage limit, (h) copy a Service or any part, feature, function or user interface thereof, (i) copy Content except as permitted herein or in an Order Form or the Documentation, (j) frame or mirror any part of any Free Service, Service, Purchased Service or Content, (k) access any Free Service, Service, Purchased Service or Content in order to build a competitive product or service, or (l) reverse engineer any Free Service, Service, Purchased Service (to the extent such restriction is permitted by law).</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">4.5. Removal of Content and Non-projecttrt.com Applications.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">If We are required by a licensor to remove Content, or receive information that Content provided to You may violate applicable law or third-party rights, We may so notify You and in such event You will promptly remove such Content from Your systems. If We receive information that a Non-projecttrt.com Application hosted on a Free Service, Service or Purchased Service by You may violate our policies, applicable law or third-party rights, We may so notify You and in such event You will promptly disable such Non-Propared.com Application or modify the Non-projecttrt.com Application to resolve the potential violation. If You do not take required action in accordance with the above, We may disable the applicable Free Service, Service, Purchased Service, Content and/or Non-Propared.com Application until the potential violation is resolved.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="de-DE">5. NON-</span></span></span></span><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">PROJECTTRT</span></span></span></span><span style=""><span style=""><span style="font-size: 150%;">.COM PROVIDERS</span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">5.1. Acquisition of Non-projecttrt.com Products and Services.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We or third parties may make available (for example, through a Marketplace or otherwise) third-party products or services, including, for example, Non-projecttrt.com Applications and implementation and other consulting services. Any acquisition by You of such Non-projecttrt.com products or services, and any exchange of data between You and any Non-projecttrt.com provider, is solely between You and the applicable Non-projecttrt.com provider. We do not warrant or support Non-projecttrt.com Applications or other Non-projecttrt.com products or services, whether or not they are designated by Us as </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">certified</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">or otherwise, except as specified in an Order Form.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">5.2. Non-projecttrt.com Applications and Your Data.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">If You install or enable a Non-projecttrt.com Application for use with a Free Service, Service, Purchased Service or Content, You grant Us permission to allow the provider of that Non-projecttrt.com Application to access Your Data as required for the interoperation of that Non-projecttrt.com Application with the Service. We are not responsible for any disclosure, modification or deletion of Your Data resulting from access by a Non-projecttrt.com Application.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">5.3. Integration with Non-projecttrt.com Applications.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The Free Services, Services, Purchased Services or Content may contain features designed to interoperate with Non-projecttrt.com Applications. To use such features, You may be required to obtain access to Non-projecttrt.com Applications from their providers, and may be required to grant Us access to Your account(s) on the Non-projecttrt.com Applications. If the provider of a Non-projecttrt.com Application ceases to make the Non-projecttrt.com Application available for interoperation with the corresponding service features on reasonable terms, We may cease providing those service features without entitling You to any refund, credit, or other compensation.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">6. FEES AND PAYMENT FOR PURCHASED SERVICES</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">6.1. Fees. You will pay all fees specified in Order Forms.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Except as otherwise specified herein or in an Order Form, (i) fees are based on services and Content purchased and not actual usage, (ii) payment obligations are non-cancelable and fees paid are non-refundable, and (iii) quantities purchased cannot be decreased during the relevant Subscription term.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">6.2. Invoicing and Payment.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You will provide Us with valid and updated credit card information. If You provide credit card information to Us, You authorize Us to charge such credit card for all Purchased Services listed in the Order Form for the initial Subscription term and any renewal Subscription term(s) as set forth in Section 12.2 (Term of Purchased Subscriptions). Such charges shall be made in advance, either annually or in accordance with any different billing frequency stated in the applicable Order Form. If the Order Form specifies that payment will be by a method other than a credit card, We will invoice You in advance and otherwise in accordance with the relevant Order Form. Unless otherwise stated in the Order Form, invoiced charges are due net 30 days from the invoice date. You are responsible for providing complete and accurate billing and contact information to Us and notifying Us of any changes to such information.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">6.3. Overdue Charges.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">If any invoiced amount is not received by Us by the due date, then without limiting Our rights or remedies, (a) those charges may accrue late interest at the rate of 1.5% of the outstanding balance per month, or the maximum rate permitted by law, whichever is lower, and/or (b) We may condition future Subscription renewals and Order Forms on payment terms shorter than those specified in Section 6.2 (Invoicing and Payment).</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">6.4. Suspension of Service and Acceleration.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">If any amount owing by You under this or any other agreement for Our services is 30 or more days overdue (or 10 or more days overdue in the case of amounts You have authorized Us to charge to Your credit card), We may, without limiting Our other rights and remedies, accelerate Your unpaid fee obligations under such agreements so that all such obligations become immediately due and payable, and suspend Our services to You until such amounts are paid in full. We will give You at least 10 days</span></span></span></span><span style=""><span style=""><span style="">&rsquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">prior notice that Your account is overdue, in accordance with Section 13.2 (Manner of Giving Notice), before suspending services to You.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">6.5. Payment Disputes.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We will not exercise Our rights under Section6.3 (Overdue Charges) or 6.4 (Suspension of Service and Acceleration) above if You are disputing the applicable charges reasonably and in good faith and are cooperating diligently to resolve the dispute.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="pt-PT">6.6. Taxes.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Our fees do not include any taxes, levies, duties or similar governmental assessments of any nature, including, for example, value-added, sales, use or withholding taxes, assessable by any jurisdiction whatsoever (collectively, </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Taxes</span></span></span></span><span style=""><span style=""><span style="">&rdquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">). You are responsible for paying all Taxes associated with Your purchases hereunder. If We have the legal obligation to pay or collect Taxes for which You are responsible under this Section 6.6, We will invoice You and You will pay that amount unless You provide Us with a valid tax exemption certificate authorized by the appropriate taxing authority. For clarity, We are solely responsible for taxes assessable against Us based on Our income, property and employees.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">6.7. Future Functionality.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You agree that Your purchases are not contingent on the delivery of any future functionality or features, or dependent on any oral or written public comments made by Us regarding future functionality or features.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">7. PROPRIETARY RIGHTS AND LICENSES</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">7.1. Reservation of Rights.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Subject to the limited rights expressly granted hereunder, We and Our licensors reserve all of Our/their right, title and interest in and to the Free Services, Services, Purchased Services or Content, including all of Our/their related intellectual property rights. No rights are granted to You hereunder other than as expressly set forth herein.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">7.2. License by Us to Use Content.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We grant to You a worldwide, limited-term license, under Our applicable intellectual property rights and licenses, to use Content acquired by You pursuant to Order Forms, subject to those Order Forms, this Agreement and the Documentation.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">7.3. License by You to Host Your Data and Applications.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You grant Us and Our Affiliates a worldwide, limited-term license to host, copy, transmit and display Your Data, and any Non-Propared.com Applications and program code created by or for You using a Free Service, Service, Purchased Service, as necessary for Us to provide the services in accordance with this Agreement. Subject to the limited licenses granted herein, We acquire no right, title or interest from You or Your licensors under this Agreement in or to Your Data or any Non-Propared.com Application or program code.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">7.4. License by You to Use Feedback.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You grant to Us and Our Affiliates a worldwide, perpetual, irrevocable, royalty-free license to use and incorporate into the Free Services, Services, Purchased Services or Content any suggestion, enhancement request, recommendation, correction or other feedback provided by You or Users relating to the operation of such services.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">8. CONFIDENTIALITY</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">8.1. Definition of Confidential Information.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style="">&ldquo;</span><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Confidential Information</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">means all information disclosed by a party (</span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Disclosing Party</span></span></span></span><span style=""><span style=""><span style="">&rdquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">) to the other party (</span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Receiving Party</span></span></span></span><span style=""><span style=""><span style="">&rdquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">), whether orally or in writing, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure. Your Confidential Information includes Your Data; Our Confidential Information includes the Free Services, Services, Purchased Services and Content; and Confidential Information of each party includes the terms and conditions of this Agreement and all Order Forms (including pricing), as well as business and marketing plans, technology and technical information, product plans and designs, and business processes disclosed by such party. However, Confidential Information does not include any information that (i) is or becomes generally known to the public without breach of any obligation owed to the Disclosing Party, (ii) was known to the Receiving Party prior to its disclosure by the Disclosing Party without breach of any obligation owed to the Disclosing Party, (iii) is received from a third party without breach of any obligation owed to the Disclosing Party, or (iv) was independently developed by the Receiving Party.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">8.2. Protection of Confidential Information.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The Receiving Party will use the same degree of care that it uses to protect the confidentiality of its own confidential information of like kind (but not less than reasonable care) (i) not to use any Confidential Information of the Disclosing Party for any purpose outside the scope of this Agreement, and (ii) except as otherwise authorized by the Disclosing Party in writing, to limit access to Confidential Information of the Disclosing Party to those of its and its Affiliates</span></span></span></span><span style=""><span style=""><span style="">&rsquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">employees and contractors who need that access for purposes consistent with this Agreement and who have signed confidentiality agreements with the Receiving Party containing protections no less stringent than those herein. Neither party will disclose the terms of this Agreement or any Order Form to any third party other than its Affiliates, legal counsel and accountants without the other party</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s prior written consent, provided that a party that makes any such disclosure to its Affiliate, legal counsel or accountants will remain responsible for such Affiliate</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s, legal counsel</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s or accountant</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s compliance with this Section 8.2.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">8.3. Compelled Disclosure.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The Receiving Party may disclose Confidential Information of the Disclosing Party to the extent compelled by law to do so, provided the Receiving Party gives the Disclosing Party prior notice of the compelled disclosure (to the extent legally permitted) and reasonable assistance, at the Disclosing Party</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s cost, if the Disclosing Party wishes to contest the disclosure. If the Receiving Party is compelled by law to disclose the Disclosing Party</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s Confidential Information as part of a civil proceeding to which the Disclosing Party is a party, and the Disclosing Party is not contesting the disclosure, the Disclosing Party will reimburse the Receiving Party for its reasonable cost of compiling and providing secure access to that Confidential Information.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">9. REPRESENTATIONS, WARRANTIES, EXCLUSIVE REMEDIES AND DISCLAIMERS</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">9.1.Representations.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Each party represents that it has validly entered into this Agreement and has the legal power to do so.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">9.2. Our Warranties.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">We warrant that this Agreement, the Order Forms and the Documentation accurately describe the applicable administrative, physical, and technical safeguards for protection of the security, confidentiality and integrity of Your Data. For any breach of an above warranty, Your exclusive remedies are those described in Sections 12.3 (Termination) and 12.4 (Refund or Payment upon Termination).</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">9.3. Disclaimers.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="de-DE">EXCEPT AS EXPRESSLY PROVIDED HEREIN, NEITHER PARTY MAKES ANY WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, AND EACH PARTY SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. CONTENT ALPHA AND BETA SERVICES ARE PROVIDED </span></span></span></span><span style=""><span style=""><span style="">&ldquo;AS IS,&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">EXCLUSIVE OF ANY WARRANTY WHATSOEVER. EACH PARTY DISCLAIMS ALL LIABILITY AND INDEMNIFICATION OBLIGATIONS FOR ANY HARM OR DAMAGES CAUSED BY ANY THIRD-PARTY HOSTING PROVIDERS.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">10. INDEMNIFICATION</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">10.1. Indemnification by You.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You will defend Us against any claim, demand, suit or proceeding made or brought against Us by a third party alleging that Your Data, or Your use of any Service or Content in breach of this Agreement, infringes or misappropriates such third party</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s intellectual property rights or violates applicable law (a </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Claim Against Us</span></span></span></span><span style=""><span style=""><span style="">&rdquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">), and will indemnify Us from any damages, attorney fees and costs finally awarded against Us as a result of, or for any amounts paid by Us under a court-approved settlement of, a Claim Against Us, provided We (a) promptly give You written notice of the Claim Against Us, (b) give You sole control of the defense and settlement of the Claim Against Us (except that You may not settle any Claim Against Us unless it unconditionally releases Us of all liability), and (c) give You all reasonable assistance, at Your expense.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">10.2. Exclusive Remedy.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">This Section 10 states the indemnifying party</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s sole liability to, and the indemnified party</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s exclusive remedy against, the other party for any type of claim described in this Section 10.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">11. LIMITATION OF LIABILITY</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">11.1 Limitation of Liability.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="de-DE">NEITHER PARTY</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">S LIABILITY WITH RESPECT TO ANY SINGLE INCIDENT ARISING OUT OF OR RELATED TO THIS AGREEMENT WILL EXCEED THE AMOUNT PAID BY CUSTOMER HEREUNDER IN THE 12 MONTHS PRECEDING THE INCIDENT, PROVIDED THAT IN NO EVENT WILL EITHER PARTY</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT EXCEED THE TOTAL AMOUNT PAID BY CUSTOMER HEREUNDER. THE ABOVE LIMITATIONS WILL APPLY WHETHER AN ACTION IS IN CONTRACT OR TORT AND REGARDLESS OF THE THEORY OF LIABILITY. HOWEVER, THE ABOVE LIMITATIONS WILL NOT LIMIT CUSTOMER</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">S PAYMENT OBLIGATIONS UNDER SECTION 6 (FEES AND PAYMENT FOR PURCHASED SERVICES).</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">11.2. Exclusion of Consequential and Related Damages.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">IN NO EVENT WILL EITHER PARTY HAVE ANY LIABILITY TO THE OTHER PARTY FOR ANY LOST PROFITS, REVENUES OR INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, COVER OR PUNITIVE DAMAGES, WHETHER AN ACTION IS IN CONTRACT OR TORT AND REGARDLESS OF THE THEORY OF LIABILITY, EVEN IF A PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING DISCLAIMER WILL NOT APPLY TO THE EXTENT PROHIBITED BY LAW.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">12. TERM AND TERMINATION</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">12.1 Term of Agreement.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">This Agreement commences on the date You first accept it and continues until the expiration or termination of the later of (a) all Subscriptions hereunder, or (b) Free Services used by You.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">12.2. Term of Purchased Subscriptions.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The term of each Subscription shall be as specified in the applicable Order Form. Except as otherwise specified in an Order Form, Subscriptions will automatically renew for additional periods equal to the expiring Subscription term or one year (whichever is shorter), unless either party gives the other notice of non-renewal at least 30 days before the end of the relevant Subscription term. The per-unit pricing during any automatic renewal term will be the same as that during the immediately prior term unless We have given You written notice of a pricing increase at least 60 days before the end of that prior term, in which case the pricing increase will be effective upon renewal and thereafter.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">12.3. Termination.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">A party may terminate this Agreement for cause (i) upon 30 days written notice to the other party of a material breach if such breach remains uncured at the expiration of such period, or (ii) if the other party becomes the subject of a petition in bankruptcy or any other proceeding relating to insolvency, receivership, liquidation or assignment for the benefit of creditors.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">12.4. Refund or Payment upon Termination.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">If this Agreement is terminated by You in accordance with Section 12.3 (Termination for </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">cause</span></span></span></span><span style=""><span style=""><span style="">&rdquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">), We will refund You any prepaid fees covering the remainder of the term of all Order Forms after the effective date of termination. If this Agreement is terminated by Us in accordance with Section 12.3, You will pay any unpaid fees covering the remainder of the term of all Order Forms. In no event will termination relieve You of Your obligation to pay any fees payable to Us for the period prior to the effective date of termination.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">12.5. Your Data Portability and Deletion.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Upon the termination or expiration of this Agreement, you will not have the ability to download or export Your Data.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">12.6. Surviving Provisions.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The Sections titled </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Fees and Payment for Purchase Services,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Proprietary Rights and Licenses,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Confidentiality,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Disclaimers,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; &ldquo;Indemnification,&rdquo; &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Limitation of Liability,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Refund or Payment upon Termination,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; &ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">Notices, Governing Law and Jurisdiction,</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">and </span></span></span></span><span style=""><span style=""><span style="">&ldquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">General Provisions</span></span></span></span><span style=""><span style=""><span style="">&rdquo; </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">will survive any termination or expiration of this Agreement.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="en-US">13. NOTICES, GOVERNING LAW AND JURISDICTION</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="">13.1. Notices.</span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Except as otherwise specified in this Agreement, all notices, permissions and approvals hereunder shall be in writing and shall be deemed to have been given upon: (i) personal delivery, (ii) the second business day after mailing, (iii) the second business day after sending by confirmed facsimile, or (iv) the first business day after sending by email (provided email shall not be sufficient for notices of termination or an indemnifiable claim). Billing-related notices to You shall be addressed to the relevant billing contact designated by You. All other notices to You shall be addressed to the relevant services system administrator designated by You. All notices to be sent to the Us shall be sent to:</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Project TRT</span></span></span></span><span style=""><span style=""><span style=""><span lang="da-DK">, LLC</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Attn: Legal Affairs</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">21318 61st St Ct E</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Bonney Lake</span></span></span></span><span style=""><span style=""><span style="">, </span></span></span><span style=""><span style=""><span style=""><span lang="en-US">WA</span></span></span></span> <span style=""><span style=""><span style=""><span lang="en-US">98391</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">13.2. Agreement to Governing Law and Jurisdiction.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Each party agrees to the applicable governing law above without regard to choice or conflicts of law rules, and to the exclusive jurisdiction of the applicable courts above.</span></span></span></span></span></span></span></p><br>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="font-size: 150%;"><span lang="de-DE">14. GENERAL PROVISIONS</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="pt-PT">14.1. Export Compliance.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">The services, Content, other technology We make available, and derivatives thereof may be subject to export laws and regulations of the United States and other jurisdictions. Each party represents that it is not named on any U.S. government denied-party list. You shall not permit Users to access or use any Service or Content in a U.S.-embargoed country (currently Cuba, Iran, North Korea, Sudan or Syria) or in violation of any U.S. export law or regulation.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="fr-FR">14.2. Anti-Corruption.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">You have not received or been offered any illegal or improper bribe, kickback, payment, gift, or thing of value from any of Our employees or agents in connection with this Agreement. Reasonable gifts and entertainment provided in the ordinary course of business do not violate the above restriction. If You learn of any violation of the above restriction, You will use reasonable efforts to promptly notify Us.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">14.3 Entire Agreement and Order of Precedence.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">This Agreement is the entire agreement between You and Us regarding Your use of services and Content and supersedes all prior and contemporaneous agreements, proposals or representations, written or oral, concerning its subject matter. No modification, amendment, or waiver of any provision of this Agreement will be effective unless in writing and signed by the party against whom the modification, amendment or waiver is to be asserted. The parties agree that any term or condition stated in Your purchase order or in any other of Your order documentation (excluding Order Forms) is void. In the event of any conflict or inconsistency among the following documents, the order of precedence shall be: (1) the applicable Order Form, (2) this Agreement, and (3) the Documentation.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">14.4. Assignment.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Neither party may assign any of its rights or obligations hereunder, whether by operation of law or otherwise, without the other party</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s prior written consent (not to be unreasonably withheld); provided, however, either party may assign this Agreement in its entirety (including all Order Forms), without the other party</span></span></span></span><span style=""><span style=""><span style="">&rsquo;</span></span></span><span style=""><span style=""><span style=""><span lang="en-US">s consent to its Affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its assets. Notwithstanding the foregoing, if a party is acquired by, sells substantially all of its assets to, or undergoes a change of control in favor of, a direct competitor of the other party, then such other party may terminate this Agreement upon written notice. Notwithstanding, in the event of such a termination by You, We will not refund to You any prepaid fees covering the remainder of the term of all Subscriptions. Subject to the foregoing, this Agreement will bind and inure to the benefit of the parties, their respective successors and permitted assigns.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">14.5. Relationship of the Parties.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">This Agreement does not create a partnership, franchise, joint venture, agency, fiduciary or employment relationship between the parties.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">14.6. Third-Party Beneficiaries.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">Our Content licensors shall have the benefit of Our rights and protections hereunder with respect to the applicable Content. There are no other third-party beneficiaries under this Agreement.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style="">14.7. Waiver.</span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">No failure or delay by either party in exercising any right under this Agreement will constitute a waiver of that right.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="it-IT">14.8. Severability.</span></span></span></span></span></span></span></p>
                            <p align="left"><span style=""><span style=""><span style=""><span style=""><span style=""><span style=""><span lang="en-US">If any provision of this Agreement is held by a court of competent jurisdiction to be contrary to law, the provision will be deemed null and void, and the remaining provisions of this Agreement will remain in effect.</span></span></span></span></span></span></span></p>
                        </div>

                    </div>
                </div>
            </div>


        </div>
    </div>

</main>