<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Privacy Policy';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="aboutus terms">
        <h1><?= Html::encode($this->title) ?></h1>
<p>Aadh Datamatics Pvt. Ltd. is committed to safeguarding its users' privacy. We request all our users to read the following 'privacy policy' to understand how their personal & business information will be treated, as they make full use of our services to their benefit. This policy is applicable only to the entire network of marketplaces operated by Aadh Datamatics Pvt. Ltd and not by any other company.</p>
<h3>COLLECTION OF INFORMATION</h3>
<p>Aadh Datamatics Pvt. Ltd collects information from its users when they register to gain access to our services or at other specific instances when they are requested to provide us with their personal & business information. During registration, we ask the users for their name, email address, business information and other personal details. Once a user registers, he/she is no longer anonymous to Aadh Datamatics Pvt. Ltd and it is deemed that the user has given Aadh Datamatics Pvt. Ltd the right to send them emails/phone calls and alerts. When you are on our network and are asked for personal information, you are sharing the information with Aadh Datamatics Pvt. Ltd alone, unless it is specifically stated otherwise. Promotions that run on our network may be sponsored by companies other than Aadh Datamatics Pvt. Ltd or may be co-sponsored by Aadh Datamatics Pvt. Ltd and another company. Some or all data collected during a promotion may be shared with the sponsor. However, you can decide not to participate in the promotion if you don't want your data to be shared. We also gather usage statistics such as pages viewed, number of unique visitors, browser software, screen resolution etc. for analysis that helps us provide you improved user experience and services.</p>
<h3>USE OF PERSONAL & BUSINESS INFORMATION</h3>
<p>Aadh Datamatics Pvt. Ltd’s primary goal in collecting personal or public information is to provide the user with a customized experience on our network of sites. This includes personalized services, interactive communication and other services, few of which are completely free and remaining are paid. Business information is used to display the user's business listing or product offerings across our network to fetch maximum business opportunities for the user. In order to provide free services, Aadh Datamatics Pvt. Ltd displays advertisements based upon the site usage statistics and visitor trends. Aadh Datamatics Pvt. Ltd uses user's personal & business information to serve targeted advertisements through its websites, newsletters and customized mailers. In addition to it, once the user's personal and business information is displayed on our network, the user may start receiving business enquiries through email, phone calls or SMS notifications, from various buyers and sellers that might or might not be of their interest. Aadh Datamatics Pvt. Ltd does not exercise any control over its users for sending business enquiries to the listed members. We record buying and browsing activities of our users including but not limited to their client's contact details and profiles and uses the same to provide value-added services to our users.</p>
<h3>SHARING OF INFORMATION</h3>
<p>As a general rule, Aadh Datamatics Pvt. Ltd will not disclose or share any of the user's personally identifiable information except when Aadh Datamatics Pvt. Ltd has the user's permission or under special circumstances, such as when Aadh Datamatics Pvt. Ltd believes in good faith that the law requires it or as permitted in terms of this policy. Aadh Datamatics Pvt. Ltd does not display user email addresses or contact information on marketplace to avoid extraction by email extractors. Aadh Datamatics Pvt. Ltd may also disclose account information in special cases when we have reasons to believe that disclosing this information is necessary to identify, contact or bring legal action against someone who may be violating Aadh Datamatics Pvt. Ltd Terms of Services or may be causing injury to or interference with (either intentionally or unintentionally) Aadh Datamatics Pvt. Ltd’s rights or property, other Aadh Datamatics Pvt. Ltd network website users, or if Aadh Datamatics Pvt. Ltd deems it necessary to maintain, service, and improve its products and services. Personal information collected may be transferred and shared in the event of a sale.</p>
<h3>DISTRIBUTION OF INFORMATION</h3>
<p>Aadh Datamatics Pvt. Ltd may, from time to time, send its users emails regarding its products and services. Aadh Datamatics Pvt. Ltd constantly tries and improves the marketplace tools for better efficiency, more relevancy, innovative business matchmaking and better personal preferences. Aadh Datamatics Pvt. Ltd has many match making tools on the marketplace to be used by its users for making relevant business contacts with each other. Aadh Datamatics Pvt. Ltd may allow direct mails using its own scripts (without disclosing the email address) with respect/pertaining to the products and services of third parties that it feels may be of interest to the user or if the user has shown interest in your company for business requirement by way of our paid buyers-sellers contact services. Only Aadh Datamatics Pvt. Ltd, its registered members or its agents working under confidentiality agreements will send these direct mailers. Relevancy of the contacts made between users would depend upon the information sought & given by various users.</p>
<h3>UPDATION OF INFORMATION</h3>
<p>A user may edit his/her account information and profile by logging onto our website and/or by sending a request to info@crispdata.co.in The requested changes may take upto 30 days to appear online because of verification process and server cache policies. A user account can be deleted or deactivated, but doing so will result in the user not being able to access any members-only area of the network. Residual information will remain within our archive records.</p>
<h3>PROTECTION OF INFORMATION</h3>
<p>As with all information, Aadh Datamatics Pvt. Ltd do not sell any data in bulk to third party that can be misused for telemarketing or bulk mailing or any other wrong purposes. In addition, Aadh Datamatics Pvt. Ltd does not sell any user's personal information or business information until and unless it is permitted by the user. Any user statistics that we may provide to prospective advertisers or partners regarding product or service usage on Aadh Datamatics Pvt. Ltd network is provided in an aggregate form only and does not include any personally identifiable information about any individual user. We request our users to sign out of their Aadh Datamatics Pvt. Ltd account and close their browser window when they have finished their work. This is to ensure that others cannot access their personal or business information and correspondence, if the user shares the computer with someone else or is using a computer in a public place. Aadh Datamatics Pvt. Ltd takes necessary steps, within its limits of commercial viability and necessity, to ensure that the user's information is treated securely. Unfortunately, no data transmission over the Internet can be guaranteed to be 100% secure. As a result, while Aadh Datamatics Pvt. Ltd strives to protect the user's personal & business information, it cannot ensure the security of any information transmitted to Aadh Datamatics Pvt. Ltd and you do so at your own risk. Once Aadh Datamatics Pvt. Ltd receives your transmission, it makes best efforts to ensure its security in its systems. Please keep in mind that whenever you post personal & business information online, that is accessible to the public, you may receive unsolicited messages from other parties.</p>
<h3>CHANGES IN PRIVACY POLICY</h3>
<p>The policy may change from time to time so please check periodically.</p>
<p>Copyright Aadh Datamatics (P) Ltd. © 2019</p>

       
    </div>
</div>
